### ISSUE TITLE
Is this project still being actively maintained?

### ISSUE THREAD

**Issue by karlisup** [davidfoliveira/node-tt2#1]
Hi,
I'm looking for the best js .tt2 solution to implement in node.js project. After a small research I understood that this is the latest & most successful try to implement it. But is it still maintained?
https://twitter.com/karlis_upitis/status/740909932904652801

**Comment by davidfoliveira** [comment]
Hi @karlisup,

The project is not being actively maintained and I've got no perspective for any further developments on it.
I've developed it in order to address a specific need that we had when I was working for @sapo but although it has done it's job, it has never fully respected the TemplateToolkit2 specification.
If you have the need for a specific feature, I am happy to implement it if it doesn't take me more than a couple of days.
I am also happy to accept any pull requests from you.

**Comment by karlisup** [comment]
Hi @davidfoliveira ,

Thank you for your response! I will try to use in one of my project to understand what’s working and what still should be implemented. Have a productive week!

/ Karlis
